name: DockerHub Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install Dependencies
      run: |
        npm install
    - name: Build Docker image
      run: |
        apt-get install -y git && apt-get install -y apt-utils && apt-get install -y curl
        docker login -u ${{ secrets.DOCKER_HUB_ID }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker build --no-cache -f Dockerfile -t pstrnk/portfolio-frontend:master .
        docker push pstrnk/portfolio-frontend:master
